require "user.conf.telescope"
require "user.conf.treesitter"
require "user.conf.autopairs"
require "user.conf.comment"
require "user.conf.gitsigns"
require "user.conf.nvim-tree"
require "user.conf.bufferline"
require "user.conf.lualine"
-- require "user.conf.toggleterm"
require "user.conf.null-ls"
require "user.conf.notify"
require "user.conf.hop"
require "user.conf.luasnip"
-- require "user.conf.sessionmanger"
-- require "user.conf.project"
require "user.conf.impatient"
-- require "user.conf.alpha"
require "user.conf.indentline"
-- require "user.conf.nvim-dap"
-- require "user.conf.nvim-dap-ui"
-- require "user.conf.nvim-dap-virtualtext"
require "user.conf.aerial"
